version: '2'
services:
  default:
    links:
      - localstack:localstack
      - dynamodb-local:dynamodb-local
    ports:
      - "3000:3000"
  localstack:
    image: localstack/localstack:3.6.0
    environment:
      - SERVICES=s3:4572
      - S3_BUCKET_NAME=test-bucket
      - LOCALSTACK_URL=http://localstack:4572
    ports:
      - "4572:4572"
    volumes:
      - ./scripts/create-bucket.sh:/docker-entrypoint-initaws.d/create-bucket.sh
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
  dynamodb-local:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
     - "4573:8000"

