version: '2'
services:
  default:
    links:
      - db:db
#      - localstack:localstack
      - localstack-dynamo:localstack-dynamo
    ports:
      - "3000:3000"
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      LC_ALL: C
    ports:
      - "5432:5432"
#  localstack:
#    image: localstack/localstack:0.10.9
#    environment:
#      - SERVICES=s3:4572,dynamodb
#      - S3_BUCKET_NAME=test-bucket
#      - LOCALSTACK_URL=http://localstack:4572
#    ports:
#      - "4572:4572"
#    volumes:
#      - ./scripts/create-bucket.sh:/docker-entrypoint-initaws.d/create-bucket.sh
#      - /var/run/docker.sock:/var/run/docker.sock
#    logging:
#      driver: none
  localstack-dynamo:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DYNAMODB_SHARE_DB=1
    volumes:
      - ./scripts/ehr-transfer-tracker-db.json:/etc/localstack/init/ready.d/ehr-transfer-tracker-db.json
      - ./scripts/create-dynamodb-table.sh:/etc/localstack/init/ready.d/create-dynamodb-table.sh
    ports:
      - "4573:4566"