version: '2'
services:
  default:
    links:
      - ehr-repo:ehr-repo
  ehr-repo:
    image: ${REPOSITORY_URI}:${IMAGE_TAG}
    links:
      - db:db
      - localstack:localstack
      - dynamodb-local:dynamodb-local
    ports:
    - 3000:3000
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
      LC_ALL: C
  localstack:
    image: localstack/localstack:0.10.9
    environment:
      - SERVICES=s3:4572
      - DEBUG=true
      - PORT_WEB_UI=5555
      - LAMBDA_EXECUTOR=local
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - S3_BUCKET_NAME=test-bucket
      - LOCALSTACK_URL=http://localstack:4572
    volumes:
      - ./scripts/create-bucket.sh:/docker-entrypoint-initaws.d/create-bucket.sh
      - /var/run/docker.sock:/var/run/docker.sock
  dynamodb-local:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "4573:8000"