version: '2'
services:
  default:
    links:
      - localstack:localstack
      - dynamodb-local:dynamodb-local
    ports:
      - "3000:3000"
  localstack:
    image: localstack/localstack:3.6.0
    environment:
      - SERVICES=s3
      - S3_BUCKET_NAME=test-bucket
      - GATEWAY_LISTEN=0.0.0.0:4572
    ports:
      - "4572:4572"
    volumes:
      - ./scripts/create-bucket.sh:/etc/localstack/init/ready.d/create-bucket.sh
      - /var/run/docker.sock:/var/run/docker.sock
  dynamodb-local:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
     - "4573:8000"

