#!/bin/bash

set -Eeo pipefail

AWS_DEFAULT_REGION=eu-west-2
IMAGE_REPO_NAME=deductions/ehr-repo
NHS_SERVICE=ehr-repo

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function tf_plan {
  check_env
  operation=$1
  cd terraform

  COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
  IMAGE_TAG=${COMMIT_HASH}

  terraform init -backend-config key=${NHS_SERVICE}-${NHS_ENVIRONMENT}/terraform.tfstate
  terraform get # modules
  if [[ "${operation}" == "create" ]]; then
    terraform plan -var task_image_tag=$IMAGE_TAG -var-file=$NHS_ENVIRONMENT.tfvars -out="nhs_deployment.tfplan"
  elif [[ "${operation}" == "destroy" ]]; then
    terraform plan -var task_image_tag=$IMAGE_TAG -var-file=$NHS_ENVIRONMENT.tfvars -out="nhs_deployment.tfplan" -destroy
  else
    echo "Unknown operation (should be create or destroy), got: ${operation}"
    exit 1
  fi
}

function tf_apply {
  cd terraform
  terraform init -backend-config key=${NHS_SERVICE}-${NHS_ENVIRONMENT}/terraform.tfstate
  terraform get # modules
  terraform apply nhs_deployment.tfplan
  terraform output -json > tf-out.json
}

function docker_login {
  echo Logging in to Amazon ECR...
  eval $(dojo -c Dojofile-infra "aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION")
}

function get_aws_secret {
  secret_id=$1
  json=$(aws ssm get-parameter --with-decryption --region $AWS_DEFAULT_REGION --name $secret_id)
  if [ $? != 0 ]; then
    >&2 echo "Failed to obtain AWS secret: $secret_id"
    exit 5
  fi
  echo $json | jq -r ".Parameter.Value"
}

command="$1"
case "${command}" in
  _dep)
      echo "Running NPM Audit ..."
      npm audit
      ;;
  dep)
      dojo "./tasks _dep"
      ;;
  _build)
      rm -rf build/
      npm install
      npm run build
      ;;
  build)
      dojo "./tasks _build"
      ;;
  _coverage)
      npm install
      npm run migrate
      npm run seed-test-data
      npm run coverage
      ;;
  coverage)
        cat << EOF > .env
NODE_ENV=local
DATABASE_NAME=deductions_test
DATABASE_USER=deductions_user
DATABASE_PASSWORD=secret
DATABASE_HOST=db
S3_BUCKET_NAME=test-bucket
LOCALSTACK_URL=http://localstack:4572
EOF
      set -a
      source .env
      dojo -c Dojofile-itest "./tasks _coverage"
      ;;
  _test)
      npm install
      npm run migrate
      npm run seed-test-data
      npm run test
      ;;
  test)
  cat << EOF > .env
NODE_ENV=local
DATABASE_NAME=deductions_test
DATABASE_USER=deductions_user
DATABASE_PASSWORD=secret
DATABASE_HOST=db
S3_BUCKET_NAME=test-bucket
LOCALSTACK_URL=http://localstack:4572
EOF
      set -a
      source .env
      dojo -c Dojofile-itest "./tasks _test"
      ;;
  interactive)
  cat << EOF > .env
NODE_ENV=local
DATABASE_NAME=deductions_test
DATABASE_USER=deductions_user
DATABASE_PASSWORD=secret
DATABASE_HOST=db
EOF
      set -a
      source .env
      dojo -c Dojofile-itest
      ;;
  build_docker_local)
      REPOSITORY_URI=$IMAGE_REPO_NAME
      COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
      IMAGE_TAG=${COMMIT_HASH}
      echo Build started on `date`
      echo Building the Docker image...
      docker build -t $REPOSITORY_URI:latest .
      docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      echo Build completed on `date`
      ;;
  build_docker)
      docker_login
      AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
      REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
      ./tasks build_docker_local
      COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
      IMAGE_TAG=${COMMIT_HASH}
      docker tag $IMAGE_REPO_NAME $REPOSITORY_URI:$IMAGE_TAG
      docker tag $IMAGE_REPO_NAME $REPOSITORY_URI:latest
      echo "Pushing the Docker image...
      $REPOSITORY_URI:latest
      $REPOSITORY_URI:$IMAGE_TAG"
      docker push $REPOSITORY_URI:latest
      docker push $REPOSITORY_URI:$IMAGE_TAG
      ;;
  _test_docker)
      npm install axios
      echo "Waiting for EHR endpoint to start responding at ${EHR_URL}"
      count=1
      set +e
      while ! node infra-tests/test_health.js; do
        echo "Waiting for EHR endpoint at ${EHR_URL}"
        sleep 1
        ((count++))
        if [ 30 -le $count ]; then
          echo "Timed-out waiting for EHR endpoint at ${EHR_URL}"
          exit 5
        fi
      done
      echo "EHR endpoint at ${EHR_URL} is healthy"
      echo "Running POST /{conversationId}/message"
      node infra-tests/test_message_update.js
      echo "Running PUT /{conversationId}/message/{messageId}"
      node infra-tests/test_message_upload.js
      ;;
  test_docker_local)
      export EHR_URL="http://ehr:3000"
      export NHS_ENVIRONMENT=docker
      export DATABASE_NAME=deductions_test
      export DATABASE_USER=deductions_user
      export DATABASE_PASSWORD=secret
      export DATABASE_HOST=db
      export EHR_DOCKER_IMAGE="${EHR_DOCKER_IMAGE:-$IMAGE_REPO_NAME}"
      export S3_BUCKET_NAME="dev-ehr-repo-bucket"
      export LOCALSTACK_URL="http://localstack:4572"
      dojo -c Dojofile-dtest "./tasks _test_docker"
      ;;
  test_docker)
      # Tests that image uses variables for config and runs migration on start
      docker_login
      COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
      IMAGE_TAG=${COMMIT_HASH}
      AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
      REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      export EHR_DOCKER_IMAGE="${REPOSITORY_URI}/$IMAGE_REPO_NAME:${IMAGE_TAG}"
      ./tasks test_docker_local
      ;;
  smoke)
      check_env
      export EHR_HOST=${NHS_ENVIRONMENT}.ehr-repo.patient-deductions.nhs.uk
      export EHR_URL=http://${EHR_HOST}
      curl -i http://${EHR_HOST}/health | grep OK
      dojo "./tasks _smoke_message_endpoints"
      ;;
  _smoke_message_endpoints)
      npm install axios
      node infra-tests/test_message_upload.js
      node infra-tests/test_message_update.js
      ;;
  tf)
      check_env
      dojo -c Dojofile-infra "bash"
      ;;
  _tf_plan)
      tf_plan "$2"
      ;;
  tf_plan)
      check_env
      dojo -c Dojofile-infra "./tasks _tf_plan $2"
      ;;
  _tf_apply)
      tf_apply
      ;;
  tf_apply)
      check_env
      dojo -c Dojofile-infra "./tasks _tf_apply"
      ;;
  _wait_ecs)
      aws ecs wait services-stable \
        --region $AWS_DEFAULT_REGION \
        --cluster $NHS_ENVIRONMENT-deductions-core-ecs-cluster \
        --services $NHS_ENVIRONMENT-ehr-repo-service
      ;;
  wait_ecs)
      check_env
      dojo -c Dojofile-infra "./tasks _wait_ecs"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
