format_version: 4
pipelines:
  "prm-deductions-ehr-repository":
    group: repository
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
    stages:
      - build:
          clean_workspace: true
          jobs:
            test_lint:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_lint
            test_unit:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_unit
            test_integration:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_integration
            coverage:
              artifacts:
                - build:
                    source: coverage/lcov-report
              tabs:
                coverage: lcov-report/index.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_coverage
            build_artifacts:
              resources:
                - docker
              artifacts:
                - build:
                    source: build
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: build_artifacts
                    source: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
      - test_docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_docker
