format_version: 4
pipelines:
  'prm-deductions-ehr-repository.canary':
    group: deductions-canary
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
    timer:
      spec: 0 0 8 ? * MON,TUE,WED,THU,FRI *
    stages:
      - update:
          clean_workspace: true
          approval: manual
          jobs:
            update_package_json:
              artifacts:
                - build:
                    source: package.json
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks update_package_json
      - test:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: update
                    job: update_package_json
                    source: package.json
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_unit
                - exec:
                    run_if: failed
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks send_dead_canary_message
            integration:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: update
                    job: update_package_json
                    source: package.json
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_integration
                - exec:
                    run_if: failed
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks send_dead_canary_message
      - audit:
          clean_workspace: true
          jobs:
            audit:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: update
                    job: update_package_json
                    source: package.json
                    is_file: yes
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dep
                - exec:
                    run_if: failed
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks send_dead_canary_message
      - communication:
          clean_workspace: true
          jobs:
            send_updates:
              resources:
                - docker
              artifacts:
                - build:
                    source: outdated-dependencies.txt
              tabs:
                Updates: outdated-dependencies.txt
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks list_outdated
