format_version: 4
common:
  plan_job: &plan_job
    resources:
      - docker
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks create_secrets
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_certs create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_db_roles create

  deploy_job: &deploy_job
    resources:
      - docker
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply_certs
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply_db_roles
      # Applies permissions for migration_role
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks grant_db_permissions
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks run_db_migrations
      # Applies permissions for application_role for tables created during migration
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks grant_db_permissions
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
pipelines:
  "prm-deductions-ehr-repository.dev":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-ehr-repository
        stage: test_docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            deploy: *plan_job
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy_job
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_functional

  "prm-deductions-ehr-repository.test":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
      dev_env:
        pipeline: prm-deductions-ehr-repository.dev
        stage: functional
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - promote_docker_image:
            resources:
              - docker
            clean_workspace: true
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks promote_docker_image
      - plan:
          clean_workspace: true
          jobs:
            deploy: *plan_job
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy_job
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_functional
      - performance:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_performance

  "prm-deductions-ehr-repository.pre-prod":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_pre_prod
      test_env:
        pipeline: prm-deductions-ehr-repository.test
        stage: functional
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan:
          jobs:
            deploy: *plan_job
      - deploy:
          jobs:
            deploy: *deploy_job
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_functional
      - performance:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_performance
