format_version: 4
common:
  plan_certs: &plan_certs
    resources:
      - docker
    artifacts:
      - build:
          source: terraform/certs_deployment.tfplan
          destination: terraform/
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_certs create
  deploy_certs: &deploy_certs
    resources:
      - docker
    tasks:
      - fetch:
          stage: plan_certs
          job: plan
          source: terraform/certs_deployment.tfplan
          destination: terraform/
          is_file: yes
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply_certs
  plan: &plan
    resources:
      - docker
    artifacts:
      - build:
          source: terraform/deployment.tfplan
          destination: terraform/
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
  deploy: &deploy
    resources:
      - docker
    tasks:
      - fetch:
          stage: plan
          job: plan
          source: terraform/deployment.tfplan
          destination: terraform/
          is_file: yes
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
    plan_db: &plan_db
      resources:
        - docker
      artifacts:
        - build:
            source: terraform-db-roles/db-roles.tfplan
            destination: terraform-db-roles/
      tasks:
        - exec:
            command: /bin/bash
            arguments:
              - -c
              - ./tasks tf_plan_db_roles create
    deploy_db: &deploy_db
      resources:
        - docker
      tasks:
        - fetch:
            stage: plan_db
            job: plan_db
            source: terraform-db-roles/db-roles.tfplan
            destination: terraform-db-roles/
            is_file: yes
        - exec:
            command: /bin/bash
            arguments:
              - -c
              - ./tasks tf_apply_db_roles
pipelines:
  "prm-deductions-ehr-repository.dev":
    group: repository
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-ehr-repository
        stage: test_docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan_certs:
          clean_workspace: true
          jobs:
            plan: *plan_certs
      - deploy_certs:
          clean_workspace: true
          jobs:
            deploy: *deploy_certs
      - plan_db:
          clean_workspace: true
          jobs:
            plan_db: *plan_db
      - deploy_db:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          jobs:
            deploy_db: *deploy_db
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          jobs:
            deploy: *deploy
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
  "prm-deductions-ehr-repository.test":
    group: repository
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_test
      dev_env:
        pipeline: prm-deductions-ehr-repository.dev
        stage: functional
#      e2e:
#        pipeline: continuity-e2e-tests.dev
#        stage: test
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - promote_docker_image:
            resources:
              - docker
            clean_workspace: true
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - ./tasks promote_docker_image
      - plan_certs:
          clean_workspace: true
          jobs:
            plan: *plan_certs
      - deploy_certs:
          clean_workspace: true
          jobs:
            deploy: *deploy_certs
      - plan_db:
          clean_workspace: true
          jobs:
            plan_db: *plan_db
      - deploy_db:
          clean_workspace: true
          jobs:
            deploy_db: *deploy_db
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
      - performance:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_performance
  "prm-deductions-ehr-repository.perf":
    group: repository
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_perf
      test_env:
        pipeline: prm-deductions-ehr-repository.test
        stage: functional
#      e2e:
#        pipeline: continuity-e2e-tests.test
#        stage: test
    environment_variables:
      NHS_ENVIRONMENT: perf
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan_certs:
          clean_workspace: true
          jobs:
            plan: *plan_certs
      - deploy_certs:
          clean_workspace: true
          jobs:
            deploy: *deploy_certs
      - plan_db:
          clean_workspace: true
          jobs:
            plan_db: *plan_db
      - deploy_db:
          clean_workspace: true
          jobs:
            deploy_db: *deploy_db
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
      - performance:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_performance
  "prm-deductions-ehr-repository.pre-prod":
    group: repository
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_pre_prod
      test_env:
        pipeline: prm-deductions-ehr-repository.test
        stage: functional
#      e2e:
#        pipeline: continuity-e2e-tests.test
#        stage: test
    environment_variables:
      NHS_ENVIRONMENT: pre-prod
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan_certs:
          clean_workspace: true
          jobs:
            plan: *plan_certs
      - deploy_certs:
          clean_workspace: true
          jobs:
            deploy: *deploy_certs
      - plan_db:
          clean_workspace: true
          jobs:
            plan_db: *plan_db
      - deploy_db:
          clean_workspace: true
          jobs:
            deploy_db: *deploy_db
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
      - performance:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_performance
  "prm-deductions-ehr-repository.prod":
    group: repository
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: deploy_pre_prod
      pre_prod_env:
        pipeline: prm-deductions-ehr-repository.pre-prod
        stage: functional
    environment_variables:
      NHS_ENVIRONMENT: prod
    stages:
      - promote_docker_image:
          resources:
            - docker
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks promote_docker_image
      - plan_certs:
          clean_workspace: true
          jobs:
            plan: *plan_certs
      - deploy_certs:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          jobs:
            deploy: *deploy_certs
      - plan_db:
          clean_workspace: true
          jobs:
            plan_db: *plan_db
      - deploy_db:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          jobs:
            deploy_db: *deploy_db
      - plan:
          clean_workspace: true
          jobs:
            plan: *plan
      - deploy:
          approval:
            type: manual
            allow_only_on_success: true
          clean_workspace: true
          jobs:
            deploy: *deploy
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
