name: End to End Test

permissions:
  contents: read  # Required for actions/checkout
  id-token: write # Required for requesting the JWT
  pull-requests: write # Required to write comments

on:
  workflow_call:

  workflow_dispatch:


jobs:
  e2e:
    environment: dev
    name: End to End Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout End to End
        uses: actions/checkout@v5
        with:
          repository: 'nhsconnect/prm-repo-e2e-tests'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          #          TODO might want a testing specific testing role
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Run End to End tests
        env:
          NHS_ENVIRONMENT: dev
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        run: |
          ./gradlew test --tests "uk.nhs.prm.e2etests.test.repositorye2etest.RepositoryE2ETest"
