name: End to End Test

on:
  workflow_call:

  workflow_dispatch:


jobs:
  e2e:
    name: End to End Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout End to End
        uses: actions/checkout@v5
        with:
          repository: 'nhsconnect/prm-repo-e2e-tests'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          #          TODO might want a testing specific testing role
          role-to-assume: ${{ secrets.IAM_ROLE_ECR_HOLDING_ACCOUNT_READ_WRITE }}
          aws-region: ${{ vars.AWS_REGION }}
          mask-aws-account-id: true

      - name: Build
        run: |
          ./gradlew build

      - name: Run End to End tests
        with:
          NHS_ENVIRONMENT: dev
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
        run: |
          ./gradlew test --tests "uk.nhs.prm.e2etests.test.RepositoryE2ETest"
