# TODO make sure working dir is correct,
# TODO check build steps required for image to be baked and published
# TODO double check permissions
# TODO maybe use build workflow to test creating and testing of container on branch
name: Build & Publish EHR Repository

on:
  push:
    branches:
      - main

permissions:
  contents: read  # Required for actions/checkout
  id-token: write # Required for requesting the JWT
  pull-requests: write # Required to write comments

jobs:
  test:
    uses: ./.github/workflows/test-ecr-repo.yml

  build_and_publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: [test]
    defaults:
      run:
        working-directory: './services/ehr-repository'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

# TODO node version?
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Clean install
        run: npm ci

      - name: build
        run: npm run build

# TODO need to configure read/write credentials for the next steps
      - name: Configure AWS Credentials (Read Only)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ECR_HOLDING_ACCOUNT_READ_ONLY }}
          aws-region: ${{ var.AWS_REGION }}
          mask-aws-account-id: true

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get docker tags
        id: get-tags
        run: |
          sha=$(echo ${{ github.sha }} | cut -c 1-8)
          echo "sha=$sha" >> $GITHUB_OUTPUT
          branchname=$(echo ${{ github.ref_name }}${{ github.head_ref }} | sed 's/^[0-9]*\/merge//g')
          echo "branchname=$branchname" >> $GITHUB_OUTPUT

      - name: docker build, tag, and publish
        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
          SHA_TAG: ${{ steps.get-tags.outputs.sha }}
          BRANCH_TAG: ${{ steps.get-tags.outputs.branchname }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$SHA_TAG -t $REGISTRY/$REPOSITORY:$BRANCH_TAG -t $REGISTRY/$REPOSITORY:latest .
          docker push $REGISTRY/$REPOSITORY:$SHA_TAG $REGISTRY/$REPOSITORY:$BRANCH_TAG