name: ehr-repo-build-and-publish
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which Environment settings to use."
        required: true
        type: string
        default: "dev"
      is_deployment:
        description: "Is workflow run on deployment"
        type: boolean
        default: false

  workflow_call:
    inputs:
      environment:
        description: "Which Environment settings to use."
        required: true
        type: string
        default: "dev"
      is_deployment:
        description: "Is workflow run on deployment"
        type: boolean
        default: false
jobs:
  helloworld:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Hello World
        run: echo "Hello, world!"
