name: Run Jest Tests on PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  jest-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npm "test:unit"

    - name: Check test results
      run: |
        if [ ${{ steps.jest-tests.outcome }} != "success" ]; then
          echo "Jest tests failed. PR cannot be merged."
          exit 1
        fi
